# Generated by Django 5.0.6 on 2024-06-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp2', '0002_alter_todo_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
